### ISSUE TITLE
Crash to desktop on loading a world

### ISSUE THREAD

**Issue by robaimes** [SonarSonic/Sonar-Core#12]
This was reported over at https://github.com/mezz/JustEnoughItems/issues/500 previously.

The game crashes to desktop when loading either a new or existing world and the stacktrace [courtesy of mezz](https://github.com/mezz/JustEnoughItems/issues/500#issuecomment-251579363) below.

```
[05:26:34] [Client thread/ERROR] [JEI/]: Error registering ingredients.
java.lang.NoClassDefFoundError: net/darkhax/tesla/capability/TeslaCapabilities
    at sonar.core.network.sync.SyncItemEnergyStorage.hasCapability(SyncItemEnergyStorage.java:53) ~[SyncItemEnergyStorage.class:?]
    at net.minecraftforge.common.capabilities.CapabilityDispatcher.hasCapability(CapabilityDispatcher.java:93) ~[CapabilityDispatcher.class:?]
    at net.minecraft.item.ItemStack.hasCapability(ItemStack.java:1039) ~[adz.class:?]
    at mezz.jei.SubtypeRegistry.getSubtypeInfo(SubtypeRegistry.java:66) ~[SubtypeRegistry.class:?]
    at mezz.jei.util.StackHelper.getUniqueIdentifierForStack(StackHelper.java:376) ~[StackHelper.class:?]
    at mezz.jei.plugins.vanilla.ingredients.ItemStackListFactory.addItemStack(ItemStackListFactory.java:101) ~[ItemStackListFactory.class:?]
    at mezz.jei.plugins.vanilla.ingredients.ItemStackListFactory.create(ItemStackListFactory.java:43) ~[ItemStackListFactory.class:?]
    at mezz.jei.plugins.vanilla.VanillaPlugin.registerIngredients(VanillaPlugin.java:91) [VanillaPlugin.class:?]
    at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:159) [ProxyCommonClient.class:?]
    at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:120) [ProxyCommonClient.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_725_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
    at net.minecraft.world.World.func_72838_d(World.java:1129) [aid.class:?]
    at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:196) [bln.class:?]
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2451) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359) [bcx.class:?]
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:276) [bll.class:?]
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) [gw.class:?]
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) [gw.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_92]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_92]
    ... 33 more
```

Although I did notice [this commit](https://github.com/SonarSonic/Sonar-Core/commit/0d305a2a4ea5baaa2b845d318d818e8f962bc1d2) that may or may not fix it. Posting here just in case this wasn't known.

**Comment by mezz** [comment]
The code called by JEI is here, it's just checking if the item has a fluid capability.
https://github.com/mezz/JustEnoughItems/blob/1.10/src/main/java/mezz/jei/SubtypeRegistry.java#L66

**Comment by SonarSonic** [comment]
@iamomicron What versions are you running?

**Comment by mezz** [comment]
We looked into this more and it seems to be an issue involving Tesla, not Sonar-Core. When your mod was removed, another mod crashed with the same Tesla issue. 
https://github.com/Darkhax-Minecraft/Tesla/issues/41

**Comment by robaimes** [comment]
As @mezz said, we look quite a lot further into this and it appears the issue is not your end, my apologies. Will close the issue. :)

**Comment by SonarSonic** [comment]
Thanks for letting me know
