### ISSUE TITLE
[1.10.2] java.lang.NoSuchMethodError: sonar.core.helpers.FontHelper.textCentre

### ISSUE THREAD

**Issue by Protheus** [SonarSonic/Sonar-Core#18]
**What happend:**
I was checking out on how to get more emeralds in JEI when I got the crash below.

**What should happen:**
you should be able to browse different recipes in JEI without game crash 

**Reproduce:**
1. open JEI
2. lookup emeralds diamonds 
3. browse the different options on how to get diamonds
4. game will stop responding and give below crash report

**Versions:**
MC: 1.10.2
forge: 2202

PracticalLogistics-1.10.2-2.0.0_-_alpha
SonarCore-1.10.2-3.2.2

jei_1.10.2-3.14.3.402
Calculator-1.10.2-3.1.6

**Short:**
WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.10.2-4.2.9.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)
  RebornCoreASM (RebornCore-1.10.2-2.12.1.96-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.198-universal.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.3.82-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.63-beta.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.339.jar)
  MalisisSwitchesPlugin (malisisswitches-1.10.2-3.1.0.jar)
Contact their authors BEFORE contacting forge
 
// This doesn't make any sense!
 
Time: 13/01/17 13:28
Description: Rendering screen
 
java.lang.NoSuchMethodError: sonar.core.helpers.FontHelper.textCentre(Ljava/lang/String;III)V
    at sonar.calculator.mod.integration.jei.Recipes$Analysing.drawInfo(Recipes.java:160)
    at mezz.jei.gui.recipes.RecipeLayout.draw(RecipeLayout.java:120)
    at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:202)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Pastebin:
http://pastebin.com/gvQRmkXD

**Comment by Protheus** [comment]
alpha..
