### ISSUE TITLE
NPE Crash with EnderIO

### ISSUE THREAD

**Issue by Sir-Will** [SonarSonic/Sonar-Core#28]
Version 3.2.5
```
java.lang.NullPointerException: Exception in server tick loop
	at sonar.core.energy.GenericForgeEnergyHandler.addEnergy(GenericForgeEnergyHandler.java:29)
	at sonar.core.handlers.energy.ForgeEnergyHandler.addEnergy(ForgeEnergyHandler.java:29)
	at sonar.core.helpers.EnergyHelper.performReceive(EnergyHelper.java:38)
	at sonar.core.helpers.EnergyHelper.receiveEnergy(EnergyHelper.java:29)
	at sonar.flux.connection.FluxHelper.pushEnergy(FluxHelper.java:65)
	at sonar.flux.connection.BasicFluxNetwork.receiveEnergy(BasicFluxNetwork.java:242)
	at sonar.flux.common.tileentity.TileEntityPlug.receiveEnergy(TileEntityPlug.java:42)
	at sonar.flux.common.tileentity.TileEntityPlug.receiveEnergy(TileEntityPlug.java:80)
	at crazypants.enderio.power.forge.PowerInterfaceForge.receiveEnergy(PowerInterfaceForge.java:19)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.sendPowerTo(CapBankNetwork.java:283)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.transmitEnergy(CapBankNetwork.java:258)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.tickEnd(CapBankNetwork.java:214)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:64)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:52)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_347_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by SonarSonic** [comment]
Fixed in dev
