### ISSUE TITLE
NPE When pulling items out of the algorithm assimilator with thermal dynamics

### ISSUE THREAD

**Issue by dashkal16** [SonarSonic/Sonar-Core#38]
Minecraft: 1.12.1
Forge: 14.22.0.2474
Sonar-Core: sonarcore-1.12.1-5.0.0.jar
Calculator: calculator-1.12.1-5.0.0.jar
Thermal Dynamics: ThermalDynamics-1.12-2.3.5.12-universal.jar

Setup was an algorithm assimilator on a diamond tree.
I attached a thermal dynamics signalum plated itemduct and inserted a servo to start extracting the weakened and flawless diamonds into a storage drawers drawer.
As soon as I activated the servo, the game crashed with a NPE:
```
java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[commons-lang3-3.5.jar:3.5]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206) ~[commons-lang3-3.5.jar:3.5]
	at net.minecraft.util.NonNullList.set(SourceFile:49) ~[fi.class:?]
	at sonar.core.inventory.AbstractSonarInventory.func_70299_a(AbstractSonarInventory.java:125) ~[AbstractSonarInventory.class:?]
	at sonar.core.helpers.InventoryHelper.removeStack(InventoryHelper.java:71) ~[InventoryHelper.class:?]
	at sonar.core.inventory.AbstractSonarInventory.extractItem(AbstractSonarInventory.java:213) ~[AbstractSonarInventory.class:?]
	at sonar.core.inventory.SonarInventory.extractItem(SonarInventory.java:52) ~[SonarInventory.class:?]
	at sonar.core.inventory.AbstractSonarInventory$EmbeddedHandler.extractItem(AbstractSonarInventory.java:52) ~[AbstractSonarInventory$EmbeddedHandler.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.handleItemSending(ServoItem.java:255) ~[ServoItem.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.tick(ServoItem.java:209) ~[ServoItem.class:?]
	at cofh.thermaldynamics.duct.item.GridItem.tickGrid(GridItem.java:80) ~[GridItem.class:?]
	at cofh.thermaldynamics.util.WorldGridList.tickEnd(WorldGridList.java:62) ~[WorldGridList.class:?]
	at cofh.thermaldynamics.util.TickHandler.tick(TickHandler.java:93) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1377_TickHandler_tick_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by SonarSonic** [comment]
Version 5.0.1 Fixes this.

**Comment by SonarSonic** [comment]
To clarify you need to update SonarCore and Calculator

**Comment by dashkal16** [comment]
Much appreciated.  I'll give it a test tonight.
