### ISSUE TITLE
3.0.7 Mod Sorting Cycle issue on client

### ISSUE THREAD

**Issue by kreezxil** [SonarSonic/Sonar-Core#4]
```
[18:30:19] [Client thread/ERROR] [FML]: The full error
net.minecraftforge.fml.common.toposort.ModSortingException: There was a cycle detected in the input graph, sorting is not possible
A dependency cycle was detected in the input mod set so an ordering cannot be determined
The first mod in the cycle is FMLMod:FluxNetworks{1.0.0}
The mod cycle involves:
    Dummy Container (After) @883878090 : before: [], after: []
    FMLMod:SonarCore{3.0.7} : before: [Calculator, PracticalLogistics, FluxNetworks], after: [CoFHLib, CoFHCore, CoFHAPI, WailaAPI, ForgeMultipart]
    FMLMod:FluxNetworks{1.0.0} : before: [SonarCore], after: [CoFHLib, CoFHCore, CoFHAPI, WailaAPI, ForgeMultipart]
    Dummy Container (AfterAll) @1601411457 : before: [], after: []

    at net.minecraftforge.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:197) ~[TopologicalSort.class:?]
    at net.minecraftforge.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:206) ~[TopologicalSort.class:?]
    at net.minecraftforge.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:206) ~[TopologicalSort.class:?]
    at net.minecraftforge.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:206) ~[TopologicalSort.class:?]
    at net.minecraftforge.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:206) ~[TopologicalSort.class:?]
    at net.minecraftforge.fml.common.toposort.TopologicalSort.topologicalSort(TopologicalSort.java:152) ~[TopologicalSort.class:?]
    at net.minecraftforge.fml.common.toposort.ModSorter.sort(ModSorter.java:139) ~[ModSorter.class:?]
    at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:288) [Loader.class:?]
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:525) [Loader.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:216) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by SonarSonic** [comment]
Try updating Flux Networks to 1.0.1, let me know if the issue persists.

**Comment by kreezxil** [comment]
I was using 1.0.1

**Comment by SonarSonic** [comment]
The log says 1.0.0 though. Also I can recreate this issue with 1.0.0 but not 1.0.1
