### ISSUE TITLE
Crash With Applied Llamagistics

### ISSUE THREAD

**Issue by cjburkey01** [SonarSonic/Sonar-Core#48]
So, I have Applied Llamagistics and Sonar Core (and Calculator); I imagine this crash happens because the API is different than the actual AE API(or something). Here's the actual error message:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SonarCore (sonarcore)
Caused by: java.lang.NoClassDefFoundError: appeng/api/networking/security/IActionSource
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at sonar.core.helpers.ASMLoader.getInstances(ASMLoader.java:89)
	at sonar.core.helpers.ASMLoader.getInventoryHandlers(ASMLoader.java:44)
	at sonar.core.helpers.ASMLoader.load(ASMLoader.java:37)
	at sonar.core.SonarCore.preInit(SonarCore.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber
```
If you want the full report, I have it up [HERE](https://paste.ee/p/HvIGw). Is there any way I can just disable the AE API settings? I don't see this as an error on AL's end, but if you think it is, I can ask the author.

I'm using SonarCore 1.12.2-5.0.2 and AL 1.12.1-rv5-beta-9

**Comment by AEnterprise** [comment]
applied llamagistics needs to update to the latest AE2 api (or if they have you need to update to the latest version), otherwise you're gona have to downgrade sonarcore

**Comment by cjburkey01** [comment]
Hm, ok then
