### ISSUE TITLE
Hang on SP World load

### ISSUE THREAD

**Issue by hayesj1** [SonarSonic/Sonar-Core#5]
Hello, I was just updating some Tesla mods, and Sonar Core is giving a strange error during world startup:
`
java.lang.NoSuchMethodError: sonar.core.helpers.SonarHelper.getGameProfileForUsername(Ljava/lang/String;)Lcom/mojang/authlib/GameProfile;
    at sonar.flux.network.NetworkData.func_76184_a(NetworkData.java:37) ~[NetworkData.class:?]
    at net.minecraft.world.storage.MapStorage.func_75742_a(SourceFile:52) ~[baj.class:?]
    at sonar.flux.FluxEvents.onWorldSave(FluxEvents.java:56) ~[FluxEvents.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_385_FluxEvents_onWorldSave_Save.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) ~[EventBus.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1012) ~[ls.class:?]
    at
`
Then I'm stuck hanging on the "dirt" screen. This happens on the newest SonarCore(3.0.9), which I redownloaded and tried again to be safe. [Pastebin](http://pastebin.com/PxaRmSGA) for full log.

Edit: This problem was not present before. I think I was using SonarCore 3.0.7, but there's a slight chance it was 3.0.8.

**Comment by SonarSonic** [comment]
I'll push some fixes soon

**Comment by SonarSonic** [comment]
3.0.8 should work for you on SP without issues, it would crash on MP though

**Comment by hayesj1** [comment]
Well good thing I'm primarily an SP Player :)

**Comment by SonarSonic** [comment]
This should be fixed now :)
