### ISSUE TITLE
1.12.2 - 5.0.6 Server Crash

### ISSUE THREAD

**Issue by SteveKnowless** [SonarSonic/Sonar-Core#59]
Server Crashes and will not start

Description: Exception in server tick loop

java.lang.NoSuchMethodError: sonar.core.network.sync.SyncNBTAbstract.setObject(Lsonar/core/api/nbt/INBTSyncable;)V
	at sonar.flux.connection.FluxNetworkCommon.<init>(FluxNetworkCommon.java:45)
	at sonar.flux.connection.BasicFluxNetwork.<init>(BasicFluxNetwork.java:56)
	at sonar.flux.network.NetworkData.func_76184_a(NetworkData.java:63)
	at net.minecraft.world.storage.MapStorage.func_75742_a(SourceFile:52)
	at sonar.flux.FluxEvents.onWorldLoad(FluxEvents.java:52)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_802_FluxEvents_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:309)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)

**Comment by SteveKnowless** [comment]
Updating to latest Flux Networks (3.0.4) Resolved the Issue
